# Generated by Django 2.0.4 on 2019-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_sales_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cod',
            field=models.ForeignKey(on_delete='Cascade', to='almacen.Products'),
        ),
    ]
