# Generated by Django 2.0.4 on 2019-02-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20190122_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='description',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='amoutn',
            field=models.PositiveIntegerField(verbose_name='amout'),
        ),
        migrations.AlterField(
            model_name='products',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='unitv',
            field=models.PositiveIntegerField(verbose_name='unitv'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cod',
            field=models.CharField(choices=[('k10', 'k10'), ('k20', 'k20')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unitv',
            field=models.PositiveIntegerField(),
        ),
    ]
